# Generated by Django 2.0.5 on 2019-08-19 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190819_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='currRounnd',
        ),
        migrations.AddField(
            model_name='profile',
            name='rounds',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Rounds'),
            preserve_default=False,
        ),
    ]
