# Generated by Django 2.0.5 on 2019-08-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190819_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rounds',
        ),
        migrations.AddField(
            model_name='profile',
            name='currRounnd',
            field=models.IntegerField(default=1),
        ),
    ]
