# Generated by Django 2.0.5 on 2019-08-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190821_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=70, null=True, unique=True),
        ),
    ]
