# Generated by Django 2.0.5 on 2019-08-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='curr_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Rounds',
        ),
    ]
