# Generated by Django 2.0.5 on 2019-08-23 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 23, 18, 20, 47, 682699)),
        ),
    ]
