# Generated by Django 2.0.5 on 2019-08-23 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_profile_submit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 23, 18, 36, 48, 932428, tzinfo=utc)),
        ),
    ]
