# Generated by Django 2.0.5 on 2019-08-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20190824_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='Not Available', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
