# Generated by Django 2.0.5 on 2019-10-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20190824_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='round',
            new_name='rounds',
        ),
    ]
