# Generated by Django 2.1.5 on 2020-12-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20201217_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='my_field',
        ),
        migrations.RemoveField(
            model_name='image',
            name='my_field',
        ),
        migrations.RemoveField(
            model_name='video',
            name='my_field',
        ),
    ]
