# Generated by Django 2.1.5 on 2020-12-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20201217_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='my_field',
            field=models.CharField(choices=[('audio', 'audio'), ('video', 'video'), ('image', 'image'), ('none', 'none')], max_length=1, null='true'),
            preserve_default='true',
        ),
    ]
