# Generated by Django 3.0.4 on 2021-01-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20201217_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
