# Generated by Django 3.1.4 on 2021-02-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20210110_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='track',
            field=models.FileField(upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.DeleteModel(
            name='Hint',
        ),
    ]
