# Generated by Django 3.1.4 on 2021-02-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20210203_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='cover',
            new_name='content',
        ),
    ]
