# Generated by Django 3.1.4 on 2021-02-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20210203_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
